apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: misago
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: misago
  template:
    metadata:
      labels:
        app: misago
    spec:
      containers:
      - name: misago
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:          
        - name: POSTGRES_DB
          value: {{ .Values.POSTGRES_DB }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.POSTGRES_PASSWORD }}
        - name: POSTGRES_HOST
          value: {{ .Values.POSTGRES_HOST }}
        - name: POSTGRES_USER
          value: {{ .Values.POSTGRES_USER }}
        - name: REDIS_HOST
          value: {{ .Values.REDIS_HOST }}
        image: {{ .Values.image.repository}}
        ports:
        - containerPort: {{ .Values.service.port }}