apiVersion: v1
kind: Service
metadata:
  name: misago
spec:
  type: {{ .Values.service.type }}
  selector:
    app: misago
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}